### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by beyang** [gorilla/http#23]
I want to use [Sourcegraph](https://sourcegraph.com) for http code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/gorilla/http. (It should only take 30 seconds.)

Thank you!

**Comment by davecheney** [comment]
Not at the moment, I haven't worked on this package in a few years, I'd
rather not make it easy to find.

**Comment by beyang** [comment]
ah got it, I hadn't checked the commit logs
