### ISSUE TITLE
golang.org/x/net/context support?

### ISSUE THREAD

**Issue by arschles** [gorilla/http#25]
Have the authors considered using [`golang.org/x/net/context`](http://godoc.org/golang.org/x/net/context) as a mechanism for controlling timeouts?

The idea would be that the caller would pass in a `context.Context` and implementation would cancel in-flight requests if the `<-chan struct{}` returned by `ctx.Done()` receives.

For example, `Do` would add a `context.Context` as its first argument:

``` go
func (c *Client) Do(ctx context.Context, method, url string, headers map[string][]string, body io.Reader) (client.Status, map[string][]string, io.ReadCloser, error)
```

And usage would look like:

``` go
// spend no more than 1 second from request initiation to response return
ctx, cancel := context.WithTimeout(context.Background(), 1 * time.Second) 
defer cancel()
_, err := http.Do(ctx, "POST", "http://www.gorillatoolkit.org/", make(map[string][]string), strings.NewReader("POST body goes here"))
// ...
```

I'm happy to submit a proposal pull request for this if interested, wanted to float the idea here first.

Reference material on context: https://blog.golang.org/context (see bottom near the `httpDo` func)

**Comment by elithrar** [comment]
Note that you can enforce timeouts more easily (I feel!) by setting the `Timeout` field on the `http.Client` and/or providing a custom `http.Transport` (if you want fine-grained timeout control) - https://golang.org/pkg/net/http/#Client

**Comment by arschles** [comment]
@elithrar I was thinking that adding this kind of support would encapsulate the custom `http.Transport` work that the client of this library would have to do
