### ISSUE TITLE
Return body on HTTP error

### ISSUE THREAD

**Issue by lancecarlson** [gorilla/http#28]
A lot of REST API's will spit out an error reason into the body of the response and return a 400 or 406 error code. Would it not make sense to expose this somehow?
```
if _, err := http.Get(os.Stdout, "http://localhost:8000/"); err != nil {
fmt.Println(body) ?
panic(err)
}
```

**Comment by monicaq** [comment]
Use [Client.Get](https://godoc.org/github.com/gorilla/http#Client.Get).  It returns the response body.
